/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.ac.uae.ensate.calculatrice;

/**
 *
 * @author Ismail Abdelouahab
 */
public class Fenêtre extends javax.swing.JFrame {

    String nombreAffiché;
    double nombre1, nombre2;
    Operation operation;
    boolean operationOn=false;
    boolean on=false;
    public Fenêtre() {
        initComponents();
    }
    
    private void afficher(String nombre){
        if(LabelAffichage.getText().equals("0") || operationOn){
            nombreAffiché = nombre;
            operationOn = false;
        }
        else{
            nombreAffiché = LabelAffichage.getText()+nombre;
        }
            
        LabelAffichage.setText(nombreAffiché);
    }
      private boolean contientVirgule(String nombre){
          return nombre.contains(".");
      }
      
      private void operation(Operation op){
           nombre1 = Double.parseDouble(LabelAffichage.getText());
        operation = op;
        operationOn = true;
      }
      
      private String enleverVirgule(String nombre){
          if(Double.parseDouble(nombre)==Math.floor(Double.parseDouble(nombre)))
              nombre = nombre.substring(0, nombreAffiché.length()-2);
          return nombre;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelAffichage = new javax.swing.JPanel();
        LabelAffichage = new javax.swing.JLabel();
        PanelOperations = new javax.swing.JPanel();
        ON = new javax.swing.JRadioButton();
        OFF = new javax.swing.JRadioButton();
        Clear = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Inverse = new javax.swing.JButton();
        Square = new javax.swing.JButton();
        RacineCarre = new javax.swing.JButton();
        Somme = new javax.swing.JButton();
        sept = new javax.swing.JButton();
        huit = new javax.swing.JButton();
        neuf = new javax.swing.JButton();
        Soustraction = new javax.swing.JButton();
        quatre = new javax.swing.JButton();
        cinq = new javax.swing.JButton();
        six = new javax.swing.JButton();
        Multiplication = new javax.swing.JButton();
        un = new javax.swing.JButton();
        deux = new javax.swing.JButton();
        trois = new javax.swing.JButton();
        Division = new javax.swing.JButton();
        Negatif = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        Virgule = new javax.swing.JButton();
        Egale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelAffichage.setBackground(new java.awt.Color(255, 255, 255));
        LabelAffichage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelAffichage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelAffichage.setOpaque(true);

        javax.swing.GroupLayout PanelAffichageLayout = new javax.swing.GroupLayout(PanelAffichage);
        PanelAffichage.setLayout(PanelAffichageLayout);
        PanelAffichageLayout.setHorizontalGroup(
            PanelAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAffichageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAffichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelAffichageLayout.setVerticalGroup(
            PanelAffichageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAffichageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAffichage, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOperations.setLayout(new java.awt.GridLayout(6, 4, 4, 4));

        buttonGroup1.add(ON);
        ON.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ON.setText("ON");
        ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ma/ac/uae/ensate/calculatrice/840513.png"))); // NOI18N
        ON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONActionPerformed(evt);
            }
        });
        PanelOperations.add(ON);

        buttonGroup1.add(OFF);
        OFF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OFF.setSelected(true);
        OFF.setText("OFF");
        OFF.setIcon(new javax.swing.ImageIcon("D:\\projetCalculatrice\\src\\main\\java\\ma\\ac\\uae\\ensate\\calculatrice\\2550435.png")); // NOI18N
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });
        PanelOperations.add(OFF);

        Clear.setBackground(new java.awt.Color(255, 204, 51));
        Clear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        PanelOperations.add(Clear);

        Delete.setBackground(new java.awt.Color(255, 102, 102));
        Delete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Delete.setText("<--");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        PanelOperations.add(Delete);

        Inverse.setBackground(new java.awt.Color(102, 204, 255));
        Inverse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Inverse.setText("1/X");
        Inverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InverseActionPerformed(evt);
            }
        });
        PanelOperations.add(Inverse);

        Square.setBackground(new java.awt.Color(102, 204, 255));
        Square.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Square.setText("X²");
        Square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareActionPerformed(evt);
            }
        });
        PanelOperations.add(Square);

        RacineCarre.setBackground(new java.awt.Color(102, 204, 255));
        RacineCarre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RacineCarre.setText("√X");
        RacineCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RacineCarreActionPerformed(evt);
            }
        });
        PanelOperations.add(RacineCarre);

        Somme.setBackground(new java.awt.Color(102, 204, 255));
        Somme.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Somme.setText("+");
        Somme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SommeActionPerformed(evt);
            }
        });
        PanelOperations.add(Somme);

        sept.setBackground(new java.awt.Color(255, 255, 153));
        sept.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sept.setText("7");
        sept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                septActionPerformed(evt);
            }
        });
        PanelOperations.add(sept);

        huit.setBackground(new java.awt.Color(255, 255, 153));
        huit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        huit.setText("8");
        huit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huitActionPerformed(evt);
            }
        });
        PanelOperations.add(huit);

        neuf.setBackground(new java.awt.Color(255, 255, 153));
        neuf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        neuf.setText("9");
        neuf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neufActionPerformed(evt);
            }
        });
        PanelOperations.add(neuf);

        Soustraction.setBackground(new java.awt.Color(102, 204, 255));
        Soustraction.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Soustraction.setText("-");
        Soustraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoustractionActionPerformed(evt);
            }
        });
        PanelOperations.add(Soustraction);

        quatre.setBackground(new java.awt.Color(255, 255, 153));
        quatre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        quatre.setText("4");
        quatre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatreActionPerformed(evt);
            }
        });
        PanelOperations.add(quatre);

        cinq.setBackground(new java.awt.Color(255, 255, 153));
        cinq.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cinq.setText("5");
        cinq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinqActionPerformed(evt);
            }
        });
        PanelOperations.add(cinq);

        six.setBackground(new java.awt.Color(255, 255, 153));
        six.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        PanelOperations.add(six);

        Multiplication.setBackground(new java.awt.Color(102, 204, 255));
        Multiplication.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Multiplication.setText("*");
        Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicationActionPerformed(evt);
            }
        });
        PanelOperations.add(Multiplication);

        un.setBackground(new java.awt.Color(255, 255, 153));
        un.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        un.setText("1");
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        PanelOperations.add(un);

        deux.setBackground(new java.awt.Color(255, 255, 153));
        deux.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        deux.setText("2");
        deux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deuxActionPerformed(evt);
            }
        });
        PanelOperations.add(deux);

        trois.setBackground(new java.awt.Color(255, 255, 153));
        trois.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        trois.setText("3");
        trois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troisActionPerformed(evt);
            }
        });
        PanelOperations.add(trois);

        Division.setBackground(new java.awt.Color(102, 204, 255));
        Division.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Division.setText("/");
        Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisionActionPerformed(evt);
            }
        });
        PanelOperations.add(Division);

        Negatif.setBackground(new java.awt.Color(255, 255, 153));
        Negatif.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Negatif.setText("+/-");
        Negatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegatifActionPerformed(evt);
            }
        });
        PanelOperations.add(Negatif);

        zero.setBackground(new java.awt.Color(255, 255, 153));
        zero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        PanelOperations.add(zero);

        Virgule.setBackground(new java.awt.Color(255, 255, 153));
        Virgule.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Virgule.setText(".");
        Virgule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VirguleActionPerformed(evt);
            }
        });
        PanelOperations.add(Virgule);

        Egale.setBackground(new java.awt.Color(51, 255, 102));
        Egale.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Egale.setText("=");
        Egale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgaleActionPerformed(evt);
            }
        });
        PanelOperations.add(Egale);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAffichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelOperations, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFActionPerformed
         on = false;
        nombreAffiché = "";
          LabelAffichage.setText(nombreAffiché);
    }//GEN-LAST:event_OFFActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(on){
            nombreAffiché = LabelAffichage.getText();
            if(nombreAffiché.length()!=1)
                nombreAffiché = nombreAffiché.substring(0, nombreAffiché.length()-1);
            else
                nombreAffiché = "0";
            LabelAffichage.setText(nombreAffiché);
            
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicationActionPerformed
    if(on)
         operation(Operation.fois);
    }//GEN-LAST:event_MultiplicationActionPerformed

    private void quatreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatreActionPerformed
       if(on){
            afficher("4");
        }
    }//GEN-LAST:event_quatreActionPerformed

    private void cinqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinqActionPerformed
       if(on){
            afficher("5");
        }
    }//GEN-LAST:event_cinqActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
       if(on){
            afficher("6");
        }
    }//GEN-LAST:event_sixActionPerformed

    private void ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONActionPerformed
        on = true;
        nombreAffiché = "0";
          LabelAffichage.setText(nombreAffiché);
    }//GEN-LAST:event_ONActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        if(on==true){
            nombreAffiché = "0";
            LabelAffichage.setText(nombreAffiché);
        }
    }//GEN-LAST:event_ClearActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        if(on){
            afficher("0");
        }
    }//GEN-LAST:event_zeroActionPerformed

    private void deuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deuxActionPerformed
       if(on){
            afficher("2");
       }
    }//GEN-LAST:event_deuxActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        if(on){
            afficher("1");
        }
    }//GEN-LAST:event_unActionPerformed

    private void troisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troisActionPerformed
        if(on){
            afficher("3");
        }
    }//GEN-LAST:event_troisActionPerformed

    private void septActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_septActionPerformed
        if(on){
            afficher("7");
        }
    }//GEN-LAST:event_septActionPerformed

    private void huitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huitActionPerformed
        if(on){
            afficher("8");
        }
    }//GEN-LAST:event_huitActionPerformed

    private void neufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neufActionPerformed
       if(on){
            afficher("9");
           
        }
    }//GEN-LAST:event_neufActionPerformed

    private void SquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareActionPerformed
        if(on){nombreAffiché = LabelAffichage.getText();
        Double nombre = Double.parseDouble(nombreAffiché);
        nombre = Math.pow(nombre, 2);
        nombreAffiché = String.valueOf(nombre);
        LabelAffichage.setText(enleverVirgule(nombreAffiché));
        }
    }//GEN-LAST:event_SquareActionPerformed

    private void RacineCarreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RacineCarreActionPerformed
            if(on){nombreAffiché = LabelAffichage.getText();
        Double nombre = Double.parseDouble(nombreAffiché);
        nombre = Math.sqrt(nombre);
        nombreAffiché = String.valueOf(nombre);
        LabelAffichage.setText(enleverVirgule(nombreAffiché));
            }
    }//GEN-LAST:event_RacineCarreActionPerformed

    private void InverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InverseActionPerformed
           if(on){ nombreAffiché = LabelAffichage.getText();
        Double nombre = Double.parseDouble(nombreAffiché);
        nombre = 1/nombre;
        nombreAffiché = String.valueOf(nombre);
        LabelAffichage.setText(enleverVirgule(nombreAffiché));
           }
    }//GEN-LAST:event_InverseActionPerformed

    private void NegatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegatifActionPerformed
        if(on){ nombreAffiché = LabelAffichage.getText();
        Double nombre = Double.parseDouble(nombreAffiché);
        nombre = nombre*(-1);
        nombreAffiché = String.valueOf(nombre);
        LabelAffichage.setText(enleverVirgule(nombreAffiché));
        }
    }//GEN-LAST:event_NegatifActionPerformed

    private void VirguleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VirguleActionPerformed
        if(on){
            nombreAffiché = LabelAffichage.getText();
            if(!contientVirgule(nombreAffiché))
                 nombreAffiché = LabelAffichage.getText()+".";
        LabelAffichage.setText(nombreAffiché);
        }
    }//GEN-LAST:event_VirguleActionPerformed

    private void SommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SommeActionPerformed
     if(on)   
         operation(Operation.plus);
    }//GEN-LAST:event_SommeActionPerformed

    private void SoustractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoustractionActionPerformed
      if(on)   
          operation(Operation.moins);
    }//GEN-LAST:event_SoustractionActionPerformed

    private void DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisionActionPerformed
     if(on)   
         operation(Operation.sur);
    }//GEN-LAST:event_DivisionActionPerformed

    private void EgaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgaleActionPerformed
        if(on){
            nombre2 = Double.parseDouble(LabelAffichage.getText());
            if(operation==null)
                nombreAffiché = String.valueOf("Operation non reconnue");
            else if(operation==Operation.plus)
                nombreAffiché = String.valueOf(nombre1+nombre2);
            else if(operation==Operation.moins)
                nombreAffiché = String.valueOf(nombre1-nombre2);
            else if(operation==Operation.fois)
                nombreAffiché = String.valueOf(nombre1*nombre2);
            else
                if(nombre2!=0)
                    nombreAffiché = String.valueOf(nombre1/nombre2);
                else
                    nombreAffiché = String.valueOf("Division non définie");
        }
        LabelAffichage.setText(enleverVirgule(nombreAffiché));
    }//GEN-LAST:event_EgaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Division;
    private javax.swing.JButton Egale;
    private javax.swing.JButton Inverse;
    private javax.swing.JLabel LabelAffichage;
    private javax.swing.JButton Multiplication;
    private javax.swing.JButton Negatif;
    private javax.swing.JRadioButton OFF;
    private javax.swing.JRadioButton ON;
    private javax.swing.JPanel PanelAffichage;
    private javax.swing.JPanel PanelOperations;
    private javax.swing.JButton RacineCarre;
    private javax.swing.JButton Somme;
    private javax.swing.JButton Soustraction;
    private javax.swing.JButton Square;
    private javax.swing.JButton Virgule;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cinq;
    private javax.swing.JButton deux;
    private javax.swing.JButton huit;
    private javax.swing.JButton neuf;
    private javax.swing.JButton quatre;
    private javax.swing.JButton sept;
    private javax.swing.JButton six;
    private javax.swing.JButton trois;
    private javax.swing.JButton un;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
